# Generated by Django 3.0.4 on 2020-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mailcontent',
            field=models.TextField(),
        ),
    ]
