# Generated by Django 3.0.4 on 2020-03-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsending', '0002_auto_20200328_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailContent',
        ),
    ]
